### ISSUE TITLE
Update index.coffee to load script, or move `brain/storage-blob-brain.coffee` to `scripts/storage-blob-brain`

### ISSUE THREAD

**Issue by technicalpickles** [bfcamara/hubot-azure-scripts#2]
Reading through https://github.com/github/hubot/pull/984 I thought it was weird to suggest `"hubot-azure-scripts/brain/azure-blob-brain"` to `external-scripts.json`. I actually was surprised that worked at all initially.

For hubot scripts, we typically try to have one entry point into a package. That's where there is a `index.coffee` that loads things from `scripts`, so if you require the npm package name, you get the scripts. Given that, I recommend doing one of two things:
- update `index.coffee` to change `scripts` to `brain`
- move `brain/brain/storage-blob-brain.coffee` to `scripts`

That would simplify the README a bit.

**Comment by bfcamara** [comment]
This is by design. I want to provide the user the ability to load the scripts (there are no scripts yet indeed) without the requirement to have to use the azure storage brain. 

Imagine that this module already provides some scrips, such as  "create Azure VM", "Stop Azure VM", etc., and we just want to use the Redis or the File brain. Makes sense?

**Comment by michaelansel** [comment]
With the [standard loader snippet](https://github.com/github/generator-hubot/blob/master/generators/script/templates/index.coffee) and [core support](https://github.com/github/hubot/blob/master/src/robot.coffee#L294-L299), you can accomplish the selective behavior in a different way:

`external-scripts.json`:

``` json
{
  "hubot-azure-scripts": ["storage-blob-brain"],
  "my-other-script": ["*"]
}
```

This will result in loading `storage-blob-brain` and all scripts in `my-other-script`.

I won't go so far as to say that I _like_ that pattern, but this _is_ the intended use case.

**Comment by bfcamara** [comment]
@michaelansel  I have also mixed feelings about that approach of using an object instead of an array to specify the scripts to load. Even though it's something supported in core for a long time, it seems that it's not very well known in the community.

For example, the yo generator for hubot is currently specified as

```
[
  "hubot-diagnostics",
  "hubot-help",
  "hubot-heroku-keepalive",
  "hubot-google-images",
  "hubot-google-translate",
  "hubot-pugme",
  "hubot-maps",
  "hubot-redis-brain",
  "hubot-rules",
  "hubot-shipit",
  "hubot-youtube"
]
```

If I want to switch my brain to azure I would need to convert the array to object notation.

```
{
  "hubot-diagnostics": ["*"],
  "hubot-help": ["*"],
  "hubot-heroku-keepalive": ["*"],
  "hubot-google-images": ["*"],
  "hubot-google-translate": ["*"],
  "hubot-pugme": ["*"],
  "hubot-maps": ["*"],
  "hubot-azure-scripts": ["storage-blob-brain"],
  "hubot-rules": ["*"],
  "hubot-shipit": ["*"],
  "hubot-youtube: ["*"]"
}
```

I'm afraid that this can confuse users, when comparing to just specify the path to the file to be loaded.

**Comment by technicalpickles** [comment]
One thing I had considered suggesting originally was to make a separate `hubot-azure-blob-brain`. That would match the pattern we already have with `hubot-redis-brain`.

**Comment by technicalpickles** [comment]
It seems the path to this changed, as reported in https://github.com/github/hubot/pull/1123 . It would be nice not to change this paths, so it doesn't affect existing users.

**Comment by bfcamara** [comment]
There is now a separate package for the brain implementation: https://github.com/coryallegory/hubot-azure-brain
