### ISSUE TITLE
Add mechanism to disable brain entirely when run locally

### ISSUE THREAD

**Issue by coryallegory** [bfcamara/hubot-azure-scripts#5]
We have a number of devs in our organization who casually add/edit hubot scripts. The live deployment uses azure for hubot brain, but when testing a separate script, this lib forces users to include valid environment vars for the HUBOT_BRAIN_AZURE_STORAGE...  entries at launch, or to have the Azure storage emulator system installed locally when using HUBOT_BRAIN_USE_STORAGE_EMULATOR=true. The latter option spams the console with failed pings to port 10000.

It would be useful to be able to disable this script when isolating and testing functionality in other hubot scripts on the same bot.

**Comment by bfcamara** [comment]
Hi @coryallegory 

I've noticed that you have forked this project to include this change and also to have a separate npm package for the brain implementation.

Since I have never included any azure script (as initially thought) and that this project only includes the brain implementation, I am going to add some info in Readme to add a link to your project and npm package if one is just looking for a brain implementation for azure.

https://github.com/coryallegory/hubot-azure-brain
